In [1]:
%gui qt

from e_p_1.model import Object, Space


import numpy as np
import pyqtgraph as qt
view = qt.ImageView()

In [2]:

a = Object(size=(3, 10, 1), position=(0, 0, 6))

b = Object(size=(3, 10, 1), position=(0, 0, -6))

space = Space(space_limits=[[-5, -5, -5], [5, 5, 5]], objects=[a, b])

grids = space.build_grids()

grids = space.ambient_field(grids, direction=[0, 0, 1], magnitude=-100.0)

v = grids.voltage[0, :, :]


In [3]:


view.setImage(v)
view.show()

view.ui.histogram.hide()

view.ui.roiPlot.hide()
view.ui.normGroup.hide()

In [4]:
v

array([[   -0.,   -25.,   -50., ..., -2525., -2550., -2575.],
       [   -0.,   -25.,   -50., ..., -2525., -2550., -2575.],
       [   -0.,   -25.,   -50., ..., -2525., -2550., -2575.],
       ...,
       [   -0.,   -25.,   -50., ..., -2525., -2550., -2575.],
       [   -0.,   -25.,   -50., ..., -2525., -2550., -2575.],
       [   -0.,   -25.,   -50., ..., -2525., -2550., -2575.]],
      shape=(92, 104))

In [5]:
np.argmax([0, 1, 3])

np.int64(2)

In [6]:
import numpy as np

s = (0, 1, slice(3, 4))

q = np.mgrid[0:5, 0:5, 0:5]

print(q)

z = q[s]

print(z)

[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[2 2 2 2 2]
   [2 2 2 2 2]
   [2 2 2 2 2]
   [2 2 2 2 2]
   [2 2 2 2 2]]

  [[3 3 3 3 3]
   [3 3 3 3 3]
   [3 3 3 3 3]
   [3 3 3 3 3]
   [3 3 3 3 3]]

  [[4 4 4 4 4]
   [4 4 4 4 4]
   [4 4 4 4 4]
   [4 4 4 4 4]
   [4 4 4 4 4]]]


 [[[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]
   [4 4 4 4 4]]

  [[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]
   [4 4 4 4 4]]

  [[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]
   [4 4 4 4 4]]

  [[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]
   [4 4 4 4 4]]

  [[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]
   [4 4 4 4 4]]]


 [[[0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]]

  [[0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]]

  [[0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 

In [7]:
z = [slice(None)] * 3
z[2] = 5
tuple(z)


(slice(None, None, None), slice(None, None, None), 5)